[project]
name = "skelmis-cru"
description = "A utility helper for working with Caido request exports"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "idox>=1.5.1",
    "pypika>=0.51.1",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "ty>=0.0.38",
]

[tool.hatch.build.targets.sdist]
include = ["cru"]

[tool.hatch.build.targets.wheel]
include = ["cru"]